// auth actions
export const AUTH_USER = 'auth_user';
export const UNAUTH_USER = 'unauth_user';
export const AUTH_ERROR = 'auth_error';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const SET_USER = 'SET_USER';
// notification
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';


export const LIST_IS_LOADING = 'LIST_IS_LOADING';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED';
export const RESET_LIST = 'RESET_LIST';


export const ADD_ITEM = 'ADD_NEW_ITEM';
export const ITEM_IS_LOADING = 'ITEM_IS_LOADING';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILED = 'FETCH_ITEM_FAILED';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';

export const FETCH_HIGHLIGHT_SUCCESS = 'FETCH_HIGHLIGHT_SUCCESS';

export const INFINITE_LOAD_SUCCESS = 'INFINITE_LOAD_SUCCESS';
export const INFINITE_IS_LOADING = 'INFINITE_IS_LOADING';
export const INFINITE_LOAD_END_OF_LIST = 'INFINITE_LOAD_END_OF_LIST';
export const INFINITE_LOAD_FAIL = 'INFINITE_LOAD_FAIL';


export const SEARCH_SNIPPETS_SUCCESS = 'SEARCH_SNIPPETS_SUCCESS';
export const SEARCH_SNIPPETS_FAIL = 'SEARCH_SNIPPETS_FAIL';
export const SEARCH_SNIPPETS_SEARCHING = 'SEARCH_SNIPPETS_SEARCHING';



export const RESET_SEARCH_FORM = 'RESET_SEARCH_FORM';
